### ISSUE TITLE
Increase Income with Inflation

### ISSUE THREAD

**Issue by strinkaj** [Daynil/portfolio-doctor#1]
Income during FIRE isnt constant, it should have an option to increase retirement income with inflation, perhaps via the Consumer Price Index. (CPI)

**Comment by Daynil** [comment]
Hi strinkaj,

All calculated values in this calculator are already adjusted for inflation using CPI by default. See: https://github.com/Daynil/portfolio-doctor/blob/master/src/data/calc/portfolio-calc.ts#L691
